---
- hosts: all
  tasks:
  - name: Copy Telegraf configuration file (telegraf.conf)
    win_copy:
     src: /etc/ansible/software/telegraf/telegraf.conf
     dest: C:\Program Files\telegraf\telegraf.conf
     force: yes
