---
- hosts: all
  tasks:
  - name: Install Telegraf Agent
    win_chocolatey:
      name: telegraf
      version: 1.13.4
      state: present
  
  - name: Remove default Telegraf.conf file
    win_file:
      path: C:\Program Files\telegraf\telegraf.conf
      state: absent

  - name: Copy Telegraf configuration file (telegraf.conf)
    win_copy:
     src: '\\mbi.lab\NETLOGON\Software\Telegraf\telegraf.conf'
     dest: C:\Program Files\telegraf\telegraf.conf
     remote_src: yes

  - name: Set Telegraf service to start delayed and start it
    win_service:
      name: telegraf
      start_mode: delayed
      state: restarted
